name: advanced_haptics_example
description: Demonstrates how to use the advanced_haptics plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Add your plugin here
  advanced_haptics:
    path: ../ # This tells it to use the local plugin from the parent directory

flutter:
  uses-material-design: true
  assets:
    - assets/haptics/ # Declare the folder